caffeine.simulator {
    # The maximum number of entries in the cache
    maximum-size = 512

    dash {
        numOfNormalBuckets = 1
        numOfStashBuckets = 3
        bucketSize = 128
        # 0 - no debugging, 1 - info level, 2 - debug level
        debugMode = 2
        policy = [classiclru, lfu]
    }

    associativeCache {
        numOfBuckets = [1]
        # 0 - no debugging, 1 - info level, 2 - debug level
        debugMode = 2
        policy = [classiclru, lfu]
    }

    policies = [
        opt.Unbounded,

        dash.DashRust,
        associative.AssociativeCacheRust,
    ]

    trace {
        # files: reads from the trace file(s)
        # synthetic: reads from a synthetic generator
        source = synthetic
    }

    synthetic {
        # The number of events to generate
        events = 30

        distribution = uniform

        counter.start = 1

        # A sequence of unique integers that repeats
        repeating.items = 8

        # A sequence that is generated from the specified set uniformly randomly
        uniform {
          lower-bound = 1
          upper-bound = 100
        }
    }
}